---
- name: Setup servers
  hosts: all
  become: true

  tasks:
    - name: Create /home/workshops repo
      file:
        path: "/home/workshops"
        state: directory

    - name: Install the latest version of Apache
      package:
        name:
          - httpd
        state: latest

    - name: Install the nmap
      package:
        name:
          - nmap
        state: latest
